/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import SILVER_TEA_ROOM_SLIDING_DOORS_OPEN_MOVEMENT from "./Open";
import SILVER_TEA_ROOM_SLIDING_DOORS_CLOSE_MOVEMENT from "./Close";

export {
  SILVER_TEA_ROOM_SLIDING_DOORS_OPEN_MOVEMENT,
  SILVER_TEA_ROOM_SLIDING_DOORS_CLOSE_MOVEMENT
};
