---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fairiesd/public_html/Arcade/Opossum_Ride_Adventure
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -rf dist/* $DEPLOYPATH/
    - /bin/cp -rf dist/.htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -rf dist/.* $DEPLOYPATH/ 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH
