/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CompactOpossumRegistryGeneral } from "./General";
import { CompactOpossumAnimationRegistry } from "./Animations";
export * from "./General";
export * from "./Animations";

export interface CompactOpossumDefinition {
  id: string;
  name: string;
  colorName: string;
  bodyFurColor: string;
  outerEarColor: string;
  innerEarColor: string;
  eyeColor: string;
  noseColor: string;
  tailColor: string;
  sex: "Jill";
  shoulderHeightInches: 36; // 3 feet
  bodyWidthInches: 29;
  bodyLengthInches: 62;
  headPosture: "Perched Forward";
  hasElegantChatter: false;
  category: "compact";
}

export const COMPACT_OPOSSUMS_REGISTRY: CompactOpossumDefinition[] = [
  {
    id: "compact_gray_black",
    name: "Gray with Black Outer Ears",
    colorName: "Gray with Black Outer Ears",
    bodyFurColor: "#8D9499",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_silver_black",
    name: "Silver Gray with Black Outer Ears",
    colorName: "Silver Gray with Black Outer Ears",
    bodyFurColor: "#B0B7BD",
    outerEarColor: "#111111",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_charcoal_black",
    name: "Charcoal with Black Outer Ears",
    colorName: "Charcoal with Black Outer Ears",
    bodyFurColor: "#4B5158",
    outerEarColor: "#0D0D0D",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_ash_black",
    name: "Ash Gray with Black Outer Ears",
    colorName: "Ash Gray with Black Outer Ears",
    bodyFurColor: "#9EA7AD",
    outerEarColor: "#1E1E1E",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_slate_black",
    name: "Slate with Black Outer Ears",
    colorName: "Slate with Black Outer Ears",
    bodyFurColor: "#606A75",
    outerEarColor: "#141414",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_smoke_black",
    name: "Smoke Gray with Black Outer Ears",
    colorName: "Smoke Gray with Black Outer Ears",
    bodyFurColor: "#A2AAB0",
    outerEarColor: "#222222",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_graphite_black",
    name: "Graphite with Black Outer Ears",
    colorName: "Graphite with Black Outer Ears",
    bodyFurColor: "#3E444A",
    outerEarColor: "#0A0A0A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_pebble_black",
    name: "Pebble Gray with Black Outer Ears",
    colorName: "Pebble Gray with Black Outer Ears",
    bodyFurColor: "#889097",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_yellow_black",
    name: "Yellow with Black Outer Ears",
    colorName: "Yellow with Black Outer Ears",
    bodyFurColor: "#F6D04D",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_amber_black",
    name: "Amber with Black Outer Ears",
    colorName: "Amber with Black Outer Ears",
    bodyFurColor: "#E5A93C",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_gold_black",
    name: "Gold with Black Outer Ears",
    colorName: "Gold with Black Outer Ears",
    bodyFurColor: "#D4AF37",
    outerEarColor: "#141414",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_lemon_black",
    name: "Lemon Yellow with Black Outer Ears",
    colorName: "Lemon Yellow with Black Outer Ears",
    bodyFurColor: "#FDE047",
    outerEarColor: "#1E1E1E",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_saffron_black",
    name: "Saffron with Black Outer Ears",
    colorName: "Saffron with Black Outer Ears",
    bodyFurColor: "#F49F1C",
    outerEarColor: "#121212",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_mustard_black",
    name: "Mustard with Black Outer Ears",
    colorName: "Mustard with Black Outer Ears",
    bodyFurColor: "#D9A74A",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_canary_black",
    name: "Canary with Black Outer Ears",
    colorName: "Canary with Black Outer Ears",
    bodyFurColor: "#F7D842",
    outerEarColor: "#171717",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_flax_black",
    name: "Flax Yellow with Black Outer Ears",
    colorName: "Flax Yellow with Black Outer Ears",
    bodyFurColor: "#EEDC82",
    outerEarColor: "#202020",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_beige_cream",
    name: "Beige with Cream Outer Ears",
    colorName: "Beige with Cream Outer Ears",
    bodyFurColor: "#D9C9B2",
    outerEarColor: "#FFFDD0",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_cream_beige",
    name: "Cream with Beige Outer Ears",
    colorName: "Cream with Beige Outer Ears",
    bodyFurColor: "#FDFBF7",
    outerEarColor: "#D9C9B2",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_tan_cream",
    name: "Tan with Cream Outer Ears",
    colorName: "Tan with Cream Outer Ears",
    bodyFurColor: "#C4A482",
    outerEarColor: "#FDF4E3",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_wheat_cream",
    name: "Wheat with Cream Outer Ears",
    colorName: "Wheat with Cream Outer Ears",
    bodyFurColor: "#E4D4BA",
    outerEarColor: "#FAF0E6",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_sand_cream",
    name: "Sand with Cream Outer Ears",
    colorName: "Sand with Cream Outer Ears",
    bodyFurColor: "#C2B280",
    outerEarColor: "#F5F5DC",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_oatmeal_cream",
    name: "Oatmeal with Cream Outer Ears",
    colorName: "Oatmeal with Cream Outer Ears",
    bodyFurColor: "#D1C7BD",
    outerEarColor: "#FFF8DC",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_biscuit_cream",
    name: "Biscuit with Cream Outer Ears",
    colorName: "Biscuit with Cream Outer Ears",
    bodyFurColor: "#E2CFB4",
    outerEarColor: "#FAF2E4",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_khaki_cream",
    name: "Khaki with Cream Outer Ears",
    colorName: "Khaki with Cream Outer Ears",
    bodyFurColor: "#B8A787",
    outerEarColor: "#F5EFEB",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_red_orange",
    name: "Red with Orange Outer Ears",
    colorName: "Red with Orange Outer Ears",
    bodyFurColor: "#D9381E",
    outerEarColor: "#FF7518",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_crimson_orange",
    name: "Crimson with Orange Outer Ears",
    colorName: "Crimson with Orange Outer Ears",
    bodyFurColor: "#B81D24",
    outerEarColor: "#F97316",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_ruby_orange",
    name: "Ruby with Orange Outer Ears",
    colorName: "Ruby with Orange Outer Ears",
    bodyFurColor: "#C0262D",
    outerEarColor: "#FB923C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_scarlet_orange",
    name: "Scarlet with Orange Outer Ears",
    colorName: "Scarlet with Orange Outer Ears",
    bodyFurColor: "#E13426",
    outerEarColor: "#EA580C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_orange_red",
    name: "Orange with Red Outer Ears",
    colorName: "Orange with Red Outer Ears",
    bodyFurColor: "#F97316",
    outerEarColor: "#C0262D",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_rust_orange",
    name: "Rust with Orange Outer Ears",
    colorName: "Rust with Orange Outer Ears",
    bodyFurColor: "#A5402D",
    outerEarColor: "#F97316",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_terracotta_orange",
    name: "Terracotta with Orange Outer Ears",
    colorName: "Terracotta with Orange Outer Ears",
    bodyFurColor: "#C86446",
    outerEarColor: "#FB923C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_cinnamon_orange",
    name: "Cinnamon with Orange Outer Ears",
    colorName: "Cinnamon with Orange Outer Ears",
    bodyFurColor: "#A0522D",
    outerEarColor: "#F58231",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_brown_black",
    name: "Brown with Black Outer Ears",
    colorName: "Brown with Black Outer Ears",
    bodyFurColor: "#6F4E37",
    outerEarColor: "#141414",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_chocolate_black",
    name: "Chocolate with Black Outer Ears",
    colorName: "Chocolate with Black Outer Ears",
    bodyFurColor: "#4B3621",
    outerEarColor: "#0D0D0D",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_chestnut_black",
    name: "Chestnut with Black Outer Ears",
    colorName: "Chestnut with Black Outer Ears",
    bodyFurColor: "#854228",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_walnut_black",
    name: "Walnut with Black Outer Ears",
    colorName: "Walnut with Black Outer Ears",
    bodyFurColor: "#5C4033",
    outerEarColor: "#121212",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_mocha_black",
    name: "Mocha with Black Outer Ears",
    colorName: "Mocha with Black Outer Ears",
    bodyFurColor: "#785844",
    outerEarColor: "#161616",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_espresso_black",
    name: "Espresso with Black Outer Ears",
    colorName: "Espresso with Black Outer Ears",
    bodyFurColor: "#38281E",
    outerEarColor: "#0A0A0A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_caramel_black",
    name: "Caramel with Black Outer Ears",
    colorName: "Caramel with Black Outer Ears",
    bodyFurColor: "#A06B3E",
    outerEarColor: "#1E1E1E",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_tawny_black",
    name: "Tawny with Black Outer Ears",
    colorName: "Tawny with Black Outer Ears",
    bodyFurColor: "#9E5B32",
    outerEarColor: "#151515",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_lavender_black",
    name: "Lavender with Black Outer Ears",
    colorName: "Lavender with Black Outer Ears",
    bodyFurColor: "#BDB0D0",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_lilac_black",
    name: "Lilac with Black Outer Ears",
    colorName: "Lilac with Black Outer Ears",
    bodyFurColor: "#C4A7E7",
    outerEarColor: "#141414",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_plum_black",
    name: "Plum with Black Outer Ears",
    colorName: "Plum with Black Outer Ears",
    bodyFurColor: "#7D5276",
    outerEarColor: "#101010",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_violet_black",
    name: "Violet with Black Outer Ears",
    colorName: "Violet with Black Outer Ears",
    bodyFurColor: "#8E6DA8",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_thistle_black",
    name: "Thistle with Black Outer Ears",
    colorName: "Thistle with Black Outer Ears",
    bodyFurColor: "#D4C2D9",
    outerEarColor: "#1C1C1C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_mauve_black",
    name: "Mauve with Black Outer Ears",
    colorName: "Mauve with Black Outer Ears",
    bodyFurColor: "#99738E",
    outerEarColor: "#151515",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_iris_black",
    name: "Iris with Black Outer Ears",
    colorName: "Iris with Black Outer Ears",
    bodyFurColor: "#7E69AB",
    outerEarColor: "#121212",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_heather_black",
    name: "Heather with Black Outer Ears",
    colorName: "Heather with Black Outer Ears",
    bodyFurColor: "#A692B7",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_white_black",
    name: "White with Black Outer Ears",
    colorName: "White with Black Outer Ears",
    bodyFurColor: "#F8F9FA",
    outerEarColor: "#121212",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_alabaster_black",
    name: "Alabaster with Black Outer Ears",
    colorName: "Alabaster with Black Outer Ears",
    bodyFurColor: "#F2F0EB",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_ivory_black",
    name: "Ivory with Black Outer Ears",
    colorName: "Ivory with Black Outer Ears",
    bodyFurColor: "#FFFFF0",
    outerEarColor: "#151515",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_pearl_black",
    name: "Pearl with Black Outer Ears",
    colorName: "Pearl with Black Outer Ears",
    bodyFurColor: "#EAE6DF",
    outerEarColor: "#1A1A1A",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_snow_black",
    name: "Snow White with Black Outer Ears",
    colorName: "Snow White with Black Outer Ears",
    bodyFurColor: "#FAFAFA",
    outerEarColor: "#0D0D0D",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_linen_black",
    name: "Linen with Black Outer Ears",
    colorName: "Linen with Black Outer Ears",
    bodyFurColor: "#FAF0E6",
    outerEarColor: "#1E1E1E",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_porcelain_black",
    name: "Porcelain with Black Outer Ears",
    colorName: "Porcelain with Black Outer Ears",
    bodyFurColor: "#F5F5F7",
    outerEarColor: "#111111",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_frost_black",
    name: "Frost White with Black Outer Ears",
    colorName: "Frost White with Black Outer Ears",
    bodyFurColor: "#EEF2F6",
    outerEarColor: "#141414",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_amber_saffron",
    name: "Amber with Saffron Outer Ears",
    colorName: "Amber with Saffron Outer Ears",
    bodyFurColor: "#E5A93C",
    outerEarColor: "#F49F1C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_saffron_amber",
    name: "Saffron with Amber Outer Ears",
    colorName: "Saffron with Amber Outer Ears",
    bodyFurColor: "#F49F1C",
    outerEarColor: "#E5A93C",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_peach_cream",
    name: "Peach with Cream Outer Ears",
    colorName: "Peach with Cream Outer Ears",
    bodyFurColor: "#F4B896",
    outerEarColor: "#FAF0E6",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_apricot_cream",
    name: "Apricot with Cream Outer Ears",
    colorName: "Apricot with Cream Outer Ears",
    bodyFurColor: "#F5AF7D",
    outerEarColor: "#FFFDD0",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_olive_black",
    name: "Olive with Black Outer Ears",
    colorName: "Olive with Black Outer Ears",
    bodyFurColor: "#707A58",
    outerEarColor: "#151515",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_sage_black",
    name: "Sage with Black Outer Ears",
    colorName: "Sage with Black Outer Ears",
    bodyFurColor: "#8FA089",
    outerEarColor: "#181818",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_copper_orange",
    name: "Copper with Orange Outer Ears",
    colorName: "Copper with Orange Outer Ears",
    bodyFurColor: "#B85D3B",
    outerEarColor: "#FF7518",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  },
  {
    id: "compact_bronze_black",
    name: "Bronze with Black Outer Ears",
    colorName: "Bronze with Black Outer Ears",
    bodyFurColor: "#7A5230",
    outerEarColor: "#121212",
    innerEarColor: "#FFB6C1",
    eyeColor: "#1A202C",
    noseColor: "#FFB6C1",
    tailColor: "#FFC0CB",
    sex: "Jill",
    shoulderHeightInches: 36,
    bodyWidthInches: 29,
    bodyLengthInches: 62,
    headPosture: "Perched Forward",
    hasElegantChatter: false,
    category: "compact"
  }
];

export const CompactOpossumsRegistry = {
  General: CompactOpossumRegistryGeneral,
  Animations: CompactOpossumAnimationRegistry,
  list: COMPACT_OPOSSUMS_REGISTRY,
  count: COMPACT_OPOSSUMS_REGISTRY.length,
  getById: (id: string) => COMPACT_OPOSSUMS_REGISTRY.find(o => o.id === id)
};
