/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS from "./General";

export { RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS };
export default RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS;
