/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Building Block Module: Rastafarian Opossums In the Royal Queendom Double Brass Sliding Doors
 */

import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_CONFIG from "./General";
import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION from "./Description";
import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS from "./Description/Dimensions";
import RASTAFARIAN_ROYAL_QUEENDOM_COLOR_PALETTE from "./Animations/Color_Palette";

export {
  RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_CONFIG,
  RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION,
  RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS,
  RASTAFARIAN_ROYAL_QUEENDOM_COLOR_PALETTE
};

export const RastafarianRoyalQueendomSlidingDoors = {
  config: RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_CONFIG,
  description: RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION,
  dimensions: RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DIMENSIONS,
  palette: RASTAFARIAN_ROYAL_QUEENDOM_COLOR_PALETTE
};

export default RastafarianRoyalQueendomSlidingDoors;
