/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_OPEN_MOVEMENT from "./Open";
import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_CLOSE_MOVEMENT from "./Close";

export {
  RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_OPEN_MOVEMENT,
  RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_CLOSE_MOVEMENT
};
