/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION from "./General";

export { RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION };
export default RASTAFARIAN_ROYAL_QUEENDOM_SLIDING_DOORS_DESCRIPTION;
